services:
  flask:
    image: devendrayadav02/flask:latest
    build:
      context: ./../flask
      dockerfile: Dockerfile
    ports:
      - 7070:8080
    env_file:
      - dev.env
    secrets:
      - api_key
      - source: api_key
        target: /api_key.txt
    configs:
      - source: my_config
        target: /config-dev-v2.yaml
    environment:
      - APP_VERSION=0.1.0
      - PASSWORD
      - APP_TOKEN:${APP_TOKEN}
    volumes:
      - ./config-dev.yaml:/config-dev.yaml
      #- ./my-data:/data
      - flask_data:/data

secrets:
  api_key:
    file: api_key.txt

configs:
  my_config:
    file: ./config-dev.yaml

volumes:
  flask_data: